=== simasch/simject/tags/1.1.0/simject/src/main/resources/resources_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- resources.xml schema -->
<xsd:schema targetNamespace="http://simject.org/xml/ns/resources"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:resources="http://simject.org/xml/ns/resources"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0">
	<xsd:annotation>
		<xsd:documentation>
      @(#)resources_1_0.xsd  1.0  Jul 28 2008
    </xsd:documentation>
	</xsd:annotation>
	<xsd:element name="resources">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="resource" minOccurs="1" maxOccurs="unbounded"
					type="resources:resource" />
			</xsd:sequence>
			<xsd:attribute name="version" type="resources:version"
				fixed="1.0" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="version">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[0-9]+(\.[0-9]+)*" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="resource">
		<xsd:sequence>
				<xsd:element name="property" minOccurs="0" maxOccurs="unbounded"
					type="resources:property" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="target" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="property">
		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== simasch/simject/tags/simject-parent-1.3.0/simject/src/test/resources/META-INF/test_resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<resources xmlns="http://simject.org/xml/ns/resources"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://simject.org/xml/ns/resources http://simject.org/xml/ns/resources/resources_1_0.xsd"
	version="1.0">
	<resource type="org.simject.test.dummy.TestClass" />
	<resource type="org.simject.test.dummy.TestInterface"
		target="org.simject.test.dummy.TestImpl" />
	<resource type="org.simject.test.dummy.TestRemoteInterface"
		target="xml:http://localhost:8080/demo/remote/org.simject.test.dummy.TestRemoteInterface" />
	<resource type="javax.persistence.EntityManager" name="org.simject.demo">
		<property name="hibernate.connection.driver_class" value="com.mysql.jdbc.Driver" />
		<property name="hibernate.connection.username" value="root" />
		<property name="hibernate.connection.password" value="root" />
		<property name="hibernate.connection.url" value="jdbc:mysql://localhost/demo" />
		<property name="hibernate.format_sql" value="true" />
		<property name="dialect" value="org.hibernate.dialect.MySQLDialect" />
		<property name="hibernate.hbm2ddl.auto" value="create-drop" />
	</resource>
</resources>

=== simasch/simject/trunk/simject/src/test/resources/META-INF/test_resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<resources xmlns="http://simject.org/xml/ns/resources"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://simject.org/xml/ns/resources http://simject.org/xml/ns/resources/resources_1_0.xsd"
	version="1.0">
	<resource type="org.simject.test.dummy.TestClass" />
	<resource type="org.simject.test.dummy.TestInterface"
		target="org.simject.test.dummy.TestImpl" />
	<resource type="org.simject.test.dummy.TestRemoteInterface"
		target="xml:http://localhost:8080/demo/remote/org.simject.test.dummy.TestRemoteInterface" />
	<resource type="javax.persistence.EntityManager" name="org.simject.demo">
		<property name="hibernate.connection.driver_class" value="org.hsqldb.jdbcDriver" />
		<property name="hibernate.connection.username" value="sa" />
		<property name="hibernate.connection.password" value="" />
		<property name="hibernate.connection.url" value="jdbc:hsqldb:mem:test" />
		<property name="hibernate.format_sql" value="true" />
		<!-- property name="dialect" value="org.hibernate.dialect.MySQLDialect" / -->
		<property name="hibernate.hbm2ddl.auto" value="create-drop" />
	</resource>
</resources>
